services:
  mongo:
    image: mongo:8.0.0-rc20-noble
    ports:
      - "27017:27017"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=motdepasseadmin
    volumes:
      - mongo_database-staging:/data/db

  api:
    build:
      context: ../..
      dockerfile: docker/dockerfile/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://admin:motdepasseadmin@mongo:27017/
    depends_on:
      mongo:
        condition: service_started

volumes:
  mongo_database-staging: