version: '3.8'

services:
  mongo:
    image: mongo:8.0.0
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_ROOT_USERNAME=admin
      - MONGODB_ROOT_PASSWORD=motdepasseadmin
    ports:
      - "27017:27017"
    volumes:
      - mongo_database-dev:/data/db

  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/
    depends_on:
      mongo:
        condition: service_completed_successfully

volumes:
  mongo_database-dev: